name: epigraphhubpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - docker-compose
  - libblas
  - nodejs
  - pandas
  - pip
  - poetry
  - psycopg2
  - python 3.9.*
  - shellcheck
  - sqlalchemy
  - pip:
    - pysus
